kind: pipeline
name: default


steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
- name: build
  image: node:11.10.0
  commands:
    - npm install
    - npm run lint
    - npm run test
- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    ttl: 7
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache:/cache
- name: npm
  image: plugins/npm
  token:
    from_secret: npm_token
  email: dan@kuida.org
  when:
    event: tag
